In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

covid = pd.read_csv('D:/SMU/Data Analytics/Datasets/covid_data.csv')
covid.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
1,AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
2,AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
3,AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
4,AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN

In [3]:
covid.isnull().sum()

iso_code                                      0
continent                                  4768
location                                      0
date                                          0
total_cases                                3761
new_cases                                  3764
new_cases_smoothed                         4774
total_deaths                              13970
new_deaths                                13814
new_deaths_smoothed                        4774
total_cases_per_million                    4283
new_cases_per_million                      4286
new_cases_smoothed_per_million             5291
total_deaths_per_million                  14479
new_deaths_per_million                    14323
new_deaths_smoothed_per_million            5291
reproduction_rate                         19726
icu_patients                              91696
icu_patients_per_million                  91696
hosp_patients                             89217
hosp_patients_per_million                 89217
weekly_icu_admissions                    101025
weekly_icu_admissions_per_million        101025
weekly_hosp_admissions                   100362
weekly_hosp_admissions_per_million       100362
new_tests                                 56436
total_tests                               56768
total_tests_per_thousand                  56768
new_tests_per_thousand                    56436
new_tests_smoothed                        48982
new_tests_smoothed_per_thousand           48982
positive_rate                             52443
tests_per_case                            53041
tests_units                               47297
total_vaccinations                        84284
people_vaccinated                         85130
people_fully_vaccinated                   88004
new_vaccinations                          87212
new_vaccinations_smoothed                 71276
total_vaccinations_per_hundred            84284
people_vaccinated_per_hundred             85130
people_fully_vaccinated_per_hundred       88004
new_vaccinations_smoothed_per_million     71276
stringency_index                          16392
population                                  656
population_density                         7243
median_age                                10901
aged_65_older                             11923
aged_70_older                             11404
gdp_per_capita                            10543
extreme_poverty                           40290
cardiovasc_death_rate                     10528
diabetes_prevalence                        8158
female_smokers                            30465
male_smokers                              31508
handwashing_facilities                    56010
hospital_beds_per_thousand                18693
life_expectancy                            5137
human_development_index                   10387
excess_mortality                          98382
dtype: int64

In [10]:
covid['total_cases'].fillna(0,inplace=True)
covid['total_deaths'].fillna(0,inplace=True)
covid['new_cases'].fillna(0,inplace=True)
covid['new_cases_smoothed'].fillna(0,inplace=True)
covid['new_deaths'].fillna(0,inplace=True)
covid['new_deaths_smoothed'].fillna(0,inplace=True)
covid.isnull().sum()

iso_code                                      0
continent                                  4768
location                                      0
date                                          0
total_cases                                   0
new_cases                                     0
new_cases_smoothed                            0
total_deaths                                  0
new_deaths                                    0
new_deaths_smoothed                           0
total_cases_per_million                    4283
new_cases_per_million                      4286
new_cases_smoothed_per_million             5291
total_deaths_per_million                  14479
new_deaths_per_million                    14323
new_deaths_smoothed_per_million            5291
reproduction_rate                         19726
icu_patients                              91696
icu_patients_per_million                  91696
hosp_patients                             89217
hosp_patients_per_million                 89217
weekly_icu_admissions                    101025
weekly_icu_admissions_per_million        101025
weekly_hosp_admissions                   100362
weekly_hosp_admissions_per_million       100362
new_tests                                 56436
total_tests                               56768
total_tests_per_thousand                  56768
new_tests_per_thousand                    56436
new_tests_smoothed                        48982
new_tests_smoothed_per_thousand           48982
positive_rate                             52443
tests_per_case                            53041
tests_units                               47297
total_vaccinations                        84284
people_vaccinated                         85130
people_fully_vaccinated                   88004
new_vaccinations                          87212
new_vaccinations_smoothed                 71276
total_vaccinations_per_hundred            84284
people_vaccinated_per_hundred             85130
people_fully_vaccinated_per_hundred       88004
new_vaccinations_smoothed_per_million     71276
stringency_index                          16392
population                                  656
population_density                         7243
median_age                                10901
aged_65_older                             11923
aged_70_older                             11404
gdp_per_capita                            10543
extreme_poverty                           40290
cardiovasc_death_rate                     10528
diabetes_prevalence                        8158
female_smokers                            30465
male_smokers                              31508
handwashing_facilities                    56010
hospital_beds_per_thousand                18693
life_expectancy                            5137
human_development_index                   10387
excess_mortality                          98382
dtype: int64

In [12]:
covid.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,0.0,0.0,0.0,0.0,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
1,AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,0.0,0.0,0.0,0.0,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
2,AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,0.0,0.0,0.0,0.0,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
3,AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,0.0,0.0,0.0,0.0,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
4,AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,0.0,0.0,0.0,0.0,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN

In [17]:
#filter data based on specific countries
covid_sg = covid[covid['location']=='Singapore']
covid_us = covid[covid['location']=='United States']
covid_europe = covid[covid['continent']=='Europe']
covid_asia = covid[covid['continent']=='Asia']

In [33]:
#filter data based on cases before and after Singapore began its vaccination program
covid_sg_vacc0 = covid_sg[covid_sg['date'] < '2021-01-11']
covid_sg_vacc1 = covid_sg[covid_sg['date'] >= '2021-01-11']

In [28]:
from scipy.stats import ttest_ind
data1 = covid_sg_vacc0['new_cases']
data2 = covid_sg_vacc1['new_cases']
stat, p = ttest_ind(data1, data2)
print('stat=%.3f, p=%.3f' % (stat, p))
if p > 0.05:
    print('New average cases are not statistically lower')
else:
    print('New average cases are statistically lower')

stat=7.939, p=0.000
New average cases are statistically lower

In [29]:
from scipy.stats import ttest_ind
data1 = covid_sg_vacc0['new_deaths']
data2 = covid_sg_vacc1['new_deaths']
stat, p = ttest_ind(data1, data2)
print('stat=%.3f, p=%.3f' % (stat, p))
if p > 0.05:
    print('New average deaths are not statistically lower')
else:
    print('New average deaths are statistically lower')

stat=1.768, p=0.078
New average deaths are not statistically lower